### ISSUE TITLE
Added new features

### ISSUE THREAD

**Issue by taha23hasnain** [NeilJed/aws-sso-credentials#6]
Hi,

I added a couple of new features to the script which will be useful for the wider audience.
1. Capability to differentiate SSO and non-SSO profiles
2. Capability to get SSO credentials for all SSO profiles

When I am trying to push the branch for PR and merge, I am getting blocked. 

Please let me know how can I push my changes? 
I have attached the updated file. 

Kind regards,
Syed

**Comment by NeilJed** [comment]
Syed,

If you want to propose changes, please make a fork or the repo, make your changes to that then submit a PR to merge your fork into my main repo:

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by taha23hasnain** [comment]
Thanks. I have submitted a PR.
